version: "3"
services:
  client:
    build: ./client
    ports:
      - "5000:80"

  server:
    build: ./server
    ports:
      - "8000:8000"
    depends_on:
      - database
    environment:
      DB_URL: ${DB_URL}
    hostname: backend

  database:
    build: ./db/
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
    ports:
      - "3307:3306"
    hostname: database
