services:
  client:
    build: ./client
    ports:
      - "5000:80"

  server:
    build: ./server
    ports:
      - "8000:8000"
    depends_on:
      - database
    environment:
      - MONGO_URI=mongodb://database:27017/urldb

  database:
    image: mongo:latest
    ports:
      - 27018:27017
